import Foundation

// A simple model to hold country data.
struct Country: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let code: String
}

// A data source providing a list of countries and their ISO Alpha-2 codes.
struct CountryDataSource {

    /// Finds a country's ISO Alpha-2 code from its full name.
    /// - Parameter name: The full name of the country (e.g., "New Zealand").
    /// - Returns: The two-letter ISO code (e.g., "NZ") or nil if not found.
    static func findCode(forName name: String) -> String? {
        return countries.first { $0.name.lowercased() == name.lowercased() }?.code
    }

    static let countries: [Country] = [
        Country(name: "Afghanistan", code: "AF"),
        Country(name: "Albania", code: "AL"),
        Country(name: "Algeria", code: "DZ"),
        Country(name: "Andorra", code: "AD"),
        Country(name: "Angola", code: "AO"),
        Country(name: "Antigua and Barbuda", code: "AG"),
        Country(name: "Argentina", code: "AR"),
        Country(name: "Armenia", code: "AM"),
        Country(name: "Australia", code: "AU"),
        Country(name: "Austria", code: "AT"),
        Country(name: "Azerbaijan", code: "AZ"),
        Country(name: "Bahamas", code: "BS"),
        Country(name: "Bahrain", code: "BH"),
        Country(name: "Bangladesh", code: "BD"),
        Country(name: "Barbados", code: "BB"),
        Country(name: "Belarus", code: "BY"),
        Country(name: "Belgium", code: "BE"),
        Country(name: "Belize", code: "BZ"),
        Country(name: "Benin", code: "BJ"),
        Country(name: "Bhutan", code: "BT"),
        Country(name: "Bolivia", code: "BO"),
        Country(name: "Bosnia and Herzegovina", code: "BA"),
        Country(name: "Botswana", code: "BW"),
        Country(name: "Brazil", code: "BR"),
        Country(name: "Brunei", code: "BN"),
        Country(name: "Bulgaria", code: "BG"),
        Country(name: "Burkina Faso", code: "BF"),
        Country(name: "Burundi", code: "BI"),
        Country(name: "Cambodia", code: "KH"),
        Country(name: "Cameroon", code: "CM"),
        Country(name: "Canada", code: "CA"),
        Country(name: "Cape Verde", code: "CV"),
        Country(name: "Central African Rep", code: "CF"),
        Country(name: "Chad", code: "TD"),
        Country(name: "Chile", code: "CL"),
        Country(name: "China", code: "CN"),
        Country(name: "Colombia", code: "CO"),
        Country(name: "Comoros", code: "KM"),
        Country(name: "Congo", code: "CG"),
        Country(name: "Congo, Dem Rep", code: "CD"),
        Country(name: "Costa Rica", code: "CR"),
        Country(name: "Croatia", code: "HR"),
        Country(name: "Cuba", code: "CU"),
        Country(name: "Cyprus", code: "CY"),
        Country(name: "Czech", code: "CZ"),
        Country(name: "Denmark", code: "DK"),
        Country(name: "Djibouti", code: "DJ"),
        Country(name: "Dominica", code: "DM"),
        Country(name: "Dominican Rep", code: "DO"),
        Country(name: "Ecuador", code: "EC"),
        Country(name: "Egypt", code: "EG"),
        Country(name: "El Salvador", code: "SV"),
        Country(name: "Equatorial Guinea", code: "GQ"),
        Country(name: "Eritrea", code: "ER"),
        Country(name: "Estonia", code: "EE"),
        Country(name: "Eswatini", code: "SZ"),
        Country(name: "Ethiopia", code: "ET"),
        Country(name: "Fiji", code: "FJ"),
        Country(name: "Finland", code: "FI"),
        Country(name: "France", code: "FR"),
        Country(name: "Gabon", code: "GA"),
        Country(name: "Gambia", code: "GM"),
        Country(name: "Georgia", code: "GE"),
        Country(name: "Germany", code: "DE"),
        Country(name: "Ghana", code: "GH"),
        Country(name: "Greece", code: "GR"),
        Country(name: "Grenada", code: "GD"),
        Country(name: "Guatemala", code: "GT"),
        Country(name: "Guinea", code: "GN"),
        Country(name: "Guinea-Bissau", code: "GW"),
        Country(name: "Guyana", code: "GY"),
        Country(name: "Haiti", code: "HT"),
        Country(name: "Honduras", code: "HN"),
        Country(name: "Hong Kong", code: "HK"),
        Country(name: "Hungary", code: "HU"),
        Country(name: "Iceland", code: "IS"),
        Country(name: "India", code: "IN"),
        Country(name: "Indonesia", code: "ID"),
        Country(name: "Iran", code: "IR"),
        Country(name: "Iraq", code: "IQ"),
        Country(name: "Ireland", code: "IE"),
        Country(name: "Israel", code: "IL"),
        Country(name: "Italy", code: "IT"),
        Country(name: "Ivory Coast", code: "CI"),
        Country(name: "Jamaica", code: "JM"),
        Country(name: "Japan", code: "JP"),
        Country(name: "Jordan", code: "JO"),
        Country(name: "Kazakhstan", code: "KZ"),
        Country(name: "Kenya", code: "KE"),
        Country(name: "Kiribati", code: "KI"),
        Country(name: "Kosovo", code: "XK"),
        Country(name: "Kuwait", code: "KW"),
        Country(name: "Kyrgyzstan", code: "KG"),
        Country(name: "Laos", code: "LA"),
        Country(name: "Latvia", code: "LV"),
        Country(name: "Lebanon", code: "LB"),
        Country(name: "Lesotho", code: "LS"),
        Country(name: "Liberia", code: "LR"),
        Country(name: "Libya", code: "LY"),
        Country(name: "Liechtenstein", code: "LI"),
        Country(name: "Lithuania", code: "LT"),
        Country(name: "Luxembourg", code: "LU"),
        Country(name: "Macau", code: "MO"),
        Country(name: "Madagascar", code: "MG"),
        Country(name: "Malawi", code: "MW"),
        Country(name: "Malaysia", code: "MY"),
        Country(name: "Maldives", code: "MV"),
        Country(name: "Mali", code: "ML"),
        Country(name: "Malta", code: "MT"),
        Country(name: "Marshall Isl.", code: "MH"),
        Country(name: "Mauritania", code: "MR"),
        Country(name: "Mauritius", code: "MU"),
        Country(name: "Mexico", code: "MX"),
        Country(name: "Micronesia", code: "FM"),
        Country(name: "Moldova", code: "MD"),
        Country(name: "Monaco", code: "MC"),
        Country(name: "Mongolia", code: "MN"),
        Country(name: "Montenegro", code: "ME"),
        Country(name: "Morocco", code: "MA"),
        Country(name: "Mozambique", code: "MZ"),
        Country(name: "Myanmar", code: "MM"),
        Country(name: "Namibia", code: "NA"),
        Country(name: "Nauru", code: "NR"),
        Country(name: "Nepal", code: "NP"),
        Country(name: "Netherlands", code: "NL"),
        Country(name: "New Zealand", code: "NZ"),
        Country(name: "Nicaragua", code: "NI"),
        Country(name: "Niger", code: "NE"),
        Country(name: "Nigeria", code: "NG"),
        Country(name: "North Korea", code: "KP"),
        Country(name: "North Macedonia", code: "MK"),
        Country(name: "Norway", code: "NO"),
        Country(name: "Oman", code: "OM"),
        Country(name: "Pakistan", code: "PK"),
        Country(name: "Palau", code: "PW"),
        Country(name: "Palestinian Terr.", code: "PS"),
        Country(name: "Panama", code: "PA"),
        Country(name: "Papua New Guinea", code: "PG"),
        Country(name: "Paraguay", code: "PY"),
        Country(name: "Peru", code: "PE"),
        Country(name: "Philippines", code: "PH"),
        Country(name: "Poland", code: "PL"),
        Country(name: "Portugal", code: "PT"),
        Country(name: "Qatar", code: "QA"),
        Country(name: "Romania", code: "RO"),
        Country(name: "Russian Fed.", code: "RU"),
        Country(name: "Rwanda", code: "RW"),
        Country(name: "Samoa", code: "WS"),
        Country(name: "San Marino", code: "SM"),
        Country(name: "Sao Tome & Principe", code: "ST"),
        Country(name: "Saudi Arabia", code: "SA"),
        Country(name: "Senegal", code: "SN"),
        Country(name: "Serbia", code: "RS"),
        Country(name: "Seychelles", code: "SC"),
        Country(name: "Sierra Leone", code: "SL"),
        Country(name: "Singapore", code: "SG"),
        Country(name: "Slovakia", code: "SK"),
        Country(name: "Slovenia", code: "SI"),
        Country(name: "Solomon Islands", code: "SB"),
        Country(name: "Somalia", code: "SO"),
        Country(name: "South Africa", code: "ZA"),
        Country(name: "South Korea", code: "KR"),
        Country(name: "South Sudan", code: "SS"),
        Country(name: "Spain", code: "ES"),
        Country(name: "Sri Lanka", code: "LK"),
        Country(name: "St Kitts & Nevis", code: "KN"),
        Country(name: "St Lucia", code: "LC"),
        Country(name: "St Vincent", code: "VC"),
        Country(name: "Sudan", code: "SD"),
        Country(name: "Suriname", code: "SR"),
        Country(name: "Sweden", code: "SE"),
        Country(name: "Switzerland", code: "CH"),
        Country(name: "Syria", code: "SY"),
        Country(name: "Taiwan", code: "TW"),
        Country(name: "Tajikistan", code: "TJ"),
        Country(name: "Tanzania", code: "TZ"),
        Country(name: "Thailand", code: "TH"),
        Country(name: "Timor-Leste", code: "TL"),
        Country(name: "Togo", code: "TG"),
        Country(name: "Tonga", code: "TO"),
        Country(name: "Trinidad & Tobago", code: "TT"),
        Country(name: "Tunisia", code: "TN"),
        Country(name: "Turkmenistan", code: "TM"),
        Country(name: "Tuvalu", code: "TV"),
        Country(name: "Türkiye", code: "TR"),
        Country(name: "UAE", code: "AE"),
        Country(name: "Uganda", code: "UG"),
        Country(name: "Ukraine", code: "UA"),
        Country(name: "United Arab Emirates", code: "AE"),
        Country(name: "United Kingdom", code: "GB"),
        Country(name: "Uruguay", code: "UY"),
        Country(name: "USA", code: "US"),
        Country(name: "Uzbekistan", code: "UZ"),
        Country(name: "Vanuatu", code: "VU"),
        Country(name: "Vatican City", code: "VA"),
        Country(name: "Venezuela", code: "VE"),
        Country(name: "Vietnam", code: "VN"),
        Country(name: "Yemen", code: "YE"),
        Country(name: "Zambia", code: "ZM"),
        Country(name: "Zimbabwe", code: "ZW")
    ]
}
